name: k_responsive
description: A standard responsive, and customizable plugin everything to usage
version: 0.1.0
repository: https://github.com/trantrongkim98/k_responsive

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null